version: "3.7"
services:
  app:
    build: app
    restart: always
    volumes:
      - ./app/src:/src
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - backend-network
      - frontend-network
    privileged: true
    devices:
      - '/dev:/dev'
    ports:
      - 41234:8080
networks:
  backend-network:
  frontend-network:
